work_dir: /share/dingyuning/S2MAF/AQA7/final3
weights: /share/dingyuning/S2MAF/AQA7/final3/runs-10-500.pt
# feeder
feeder: feeder.AQA7.VideoDataset
train_feeder_args:
  debug: False
  video_dir_head: /share/AQA7/Actions
  mat_path: /share/AQA7/Split_4/split_4_train_list.mat
  label_path: /share/AQA7/train_label.pickle
  data_path: /share/AQA7/train_data.pickle
  random_choose: True
  random_move: True
  window_size: 103
  split: 'train'
  mode: 'fusion'

test_feeder_args:
  debug: False
  video_dir_head: /share/AQA7/Actions
  mat_path:  /share/AQA7/Split_4/split_4_test_list.mat
  label_path: /share/AQA7/test_label.pickle
  data_path: /share/AQA7/test_data.pickle
  clip_len: 103
  random_choose: False
  random_move: False
  window_size: 103
  split: 'test'
  mode: 'fusion'


#weights: work_dir/skating/base/runs-202-4040.pt
# model
#model: model.FTSGCNjia.Model
model: model.2MAF.Framework
model_args:
  I3D_classes: 400
  num_class: 63
  num_person: 1
  num_point: 17
  # edge_importance_weighting: True
  graph: graph.gym.Graph
  graph_args:
    labeling_mode: 'spatial'
  size: 103

optimizer: 'Adam'
#training
# device: [0,1]
# batch_size: 64
# test_batch_size: 64
device: [1]
batch_size: 16
test_batch_size: 16

#optim
base_lr: 0.0005
step: [150]
num_epoch: 100
lr_decay_rate: 0.1
warm_up_epoch: 0
weight_decay: 0

seed: 5
